# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowTitle("Домашняя бухгалтерия")
        MainWindow.setToolTip("Домашняя бухгалтерия")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setWindowFilePath("")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_bill = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_bill.sizePolicy().hasHeightForWidth())
        self.tab_bill.setSizePolicy(sizePolicy)
        self.tab_bill.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_bill.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_bill.setAutoFillBackground(True)
        self.tab_bill.setObjectName("tab_bill")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_bill)
        self.gridLayout_3.setContentsMargins(100, 10, 100, 10)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_rates = QtWidgets.QFrame(self.tab_bill)
        self.frame_rates.setMaximumSize(QtCore.QSize(800, 200))
        self.frame_rates.setAutoFillBackground(False)
        self.frame_rates.setStyleSheet("background-color: #fff;")
        self.frame_rates.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_rates.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_rates.setObjectName("frame_rates")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_rates)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(20, 9, 20, 20)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_rates_title_name = QtWidgets.QLabel(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_rates_title_name.setFont(font)
        self.label_rates_title_name.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_rates_title_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_rates_title_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_rates_title_name.setTextFormat(QtCore.Qt.AutoText)
        self.label_rates_title_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rates_title_name.setObjectName("label_rates_title_name")
        self.gridLayout_2.addWidget(self.label_rates_title_name, 0, 0, 1, 1)
        self.label_rates_title_rate = QtWidgets.QLabel(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_rates_title_rate.setFont(font)
        self.label_rates_title_rate.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_rates_title_rate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_rates_title_rate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_rates_title_rate.setTextFormat(QtCore.Qt.AutoText)
        self.label_rates_title_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rates_title_rate.setObjectName("label_rates_title_rate")
        self.gridLayout_2.addWidget(self.label_rates_title_rate, 0, 1, 1, 1)
        self.label_rates_title_date = QtWidgets.QLabel(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_rates_title_date.setFont(font)
        self.label_rates_title_date.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_rates_title_date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_rates_title_date.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_rates_title_date.setTextFormat(QtCore.Qt.AutoText)
        self.label_rates_title_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rates_title_date.setObjectName("label_rates_title_date")
        self.gridLayout_2.addWidget(self.label_rates_title_date, 0, 2, 1, 1)
        self.label_rates_evr = QtWidgets.QLabel(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_rates_evr.setFont(font)
        self.label_rates_evr.setObjectName("label_rates_evr")
        self.gridLayout_2.addWidget(self.label_rates_evr, 1, 0, 1, 1)
        self.lineEdit_rates_evr = QtWidgets.QLineEdit(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_rates_evr.setFont(font)
        self.lineEdit_rates_evr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_rates_evr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rates_evr.setReadOnly(True)
        self.lineEdit_rates_evr.setObjectName("lineEdit_rates_evr")
        self.gridLayout_2.addWidget(self.lineEdit_rates_evr, 1, 1, 1, 1)
        self.lineEdit_rates_date_evr = QtWidgets.QLineEdit(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_rates_date_evr.setFont(font)
        self.lineEdit_rates_date_evr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_rates_date_evr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rates_date_evr.setReadOnly(True)
        self.lineEdit_rates_date_evr.setObjectName("lineEdit_rates_date_evr")
        self.gridLayout_2.addWidget(self.lineEdit_rates_date_evr, 1, 2, 1, 1)
        self.label_rates_rub = QtWidgets.QLabel(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_rates_rub.setFont(font)
        self.label_rates_rub.setObjectName("label_rates_rub")
        self.gridLayout_2.addWidget(self.label_rates_rub, 2, 0, 1, 1)
        self.lineEdit_rates_rub = QtWidgets.QLineEdit(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_rates_rub.setFont(font)
        self.lineEdit_rates_rub.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_rates_rub.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rates_rub.setReadOnly(True)
        self.lineEdit_rates_rub.setObjectName("lineEdit_rates_rub")
        self.gridLayout_2.addWidget(self.lineEdit_rates_rub, 2, 1, 1, 1)
        self.lineEdit_rates_date_rub = QtWidgets.QLineEdit(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_rates_date_rub.setFont(font)
        self.lineEdit_rates_date_rub.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_rates_date_rub.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rates_date_rub.setReadOnly(True)
        self.lineEdit_rates_date_rub.setObjectName("lineEdit_rates_date_rub")
        self.gridLayout_2.addWidget(self.lineEdit_rates_date_rub, 2, 2, 1, 1)
        self.label_rates_usd = QtWidgets.QLabel(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_rates_usd.setFont(font)
        self.label_rates_usd.setObjectName("label_rates_usd")
        self.gridLayout_2.addWidget(self.label_rates_usd, 3, 0, 1, 1)
        self.lineEdit_rates_usd = QtWidgets.QLineEdit(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_rates_usd.setFont(font)
        self.lineEdit_rates_usd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_rates_usd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rates_usd.setReadOnly(True)
        self.lineEdit_rates_usd.setObjectName("lineEdit_rates_usd")
        self.gridLayout_2.addWidget(self.lineEdit_rates_usd, 3, 1, 1, 1)
        self.lineEdit_rates_date_usd = QtWidgets.QLineEdit(self.frame_rates)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_rates_date_usd.setFont(font)
        self.lineEdit_rates_date_usd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_rates_date_usd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rates_date_usd.setReadOnly(True)
        self.lineEdit_rates_date_usd.setObjectName("lineEdit_rates_date_usd")
        self.gridLayout_2.addWidget(self.lineEdit_rates_date_usd, 3, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 5)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_3.addWidget(self.frame_rates, 1, 0, 1, 1)
        self.frame_bill = QtWidgets.QFrame(self.tab_bill)
        self.frame_bill.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_bill.setBaseSize(QtCore.QSize(200, 200))
        self.frame_bill.setAutoFillBackground(False)
        self.frame_bill.setStyleSheet("background-color: #fff;")
        self.frame_bill.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_bill.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bill.setMidLineWidth(0)
        self.frame_bill.setObjectName("frame_bill")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_bill)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_bill_byn = QtWidgets.QLabel(self.frame_bill)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_bill_byn.setFont(font)
        self.label_bill_byn.setText("BYN")
        self.label_bill_byn.setObjectName("label_bill_byn")
        self.gridLayout.addWidget(self.label_bill_byn, 0, 0, 1, 1)
        self.lineEdit_usd = QtWidgets.QLineEdit(self.frame_bill)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_usd.setFont(font)
        self.lineEdit_usd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_usd.setReadOnly(True)
        self.lineEdit_usd.setObjectName("lineEdit_usd")
        self.gridLayout.addWidget(self.lineEdit_usd, 2, 1, 1, 1)
        self.label_bill_rub = QtWidgets.QLabel(self.frame_bill)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_bill_rub.setFont(font)
        self.label_bill_rub.setText("RUB")
        self.label_bill_rub.setObjectName("label_bill_rub")
        self.gridLayout.addWidget(self.label_bill_rub, 1, 0, 1, 1)
        self.lineEdit_rub = QtWidgets.QLineEdit(self.frame_bill)
        self.lineEdit_rub.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_rub.setFont(font)
        self.lineEdit_rub.setMaxLength(8)
        self.lineEdit_rub.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_rub.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rub.setReadOnly(True)
        self.lineEdit_rub.setObjectName("lineEdit_rub")
        self.gridLayout.addWidget(self.lineEdit_rub, 1, 1, 1, 1)
        self.label_bill_usd = QtWidgets.QLabel(self.frame_bill)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_bill_usd.setFont(font)
        self.label_bill_usd.setText("USD")
        self.label_bill_usd.setObjectName("label_bill_usd")
        self.gridLayout.addWidget(self.label_bill_usd, 2, 0, 1, 1)
        self.lineEdit_byn = QtWidgets.QLineEdit(self.frame_bill)
        self.lineEdit_byn.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_byn.setFont(font)
        self.lineEdit_byn.setStyleSheet("color: rgb(0, 170, 0);")
        self.lineEdit_byn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_byn.setReadOnly(True)
        self.lineEdit_byn.setObjectName("lineEdit_byn")
        self.gridLayout.addWidget(self.lineEdit_byn, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_3.addWidget(self.frame_bill, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_bill, "")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.tabWidget.addTab(self.tab_history, "")
        self.tab_planning = QtWidgets.QWidget()
        self.tab_planning.setObjectName("tab_planning")
        self.tabWidget.addTab(self.tab_planning, "")
        self.tab_write = QtWidgets.QWidget()
        self.tab_write.setObjectName("tab_write")
        self.tabWidget.addTab(self.tab_write, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.toolBar.setFont(font)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBar.setAcceptDrops(False)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionIncome = QtWidgets.QAction(MainWindow)
        self.actionIncome.setCheckable(False)
        self.actionIncome.setChecked(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/svg/download-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncome.setIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.actionIncome.setFont(font)
        self.actionIncome.setAutoRepeat(True)
        self.actionIncome.setVisible(True)
        self.actionIncome.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionIncome.setIconVisibleInMenu(True)
        self.actionIncome.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionIncome.setObjectName("actionIncome")
        self.actionOutcome = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/svg/upload-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOutcome.setIcon(icon1)
        self.actionOutcome.setObjectName("actionOutcome")
        self.actionNewCategory = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/svg/folder-plus-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewCategory.setIcon(icon2)
        self.actionNewCategory.setObjectName("actionNewCategory")
        self.actionEditCategory = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/svg/folder-open-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditCategory.setIcon(icon3)
        self.actionEditCategory.setObjectName("actionEditCategory")
        self.toolBar.addAction(self.actionIncome)
        self.toolBar.addAction(self.actionOutcome)
        self.toolBar.addAction(self.actionNewCategory)
        self.toolBar.addAction(self.actionEditCategory)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        MainWindow.iconSizeChanged['QSize'].connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_rub)
        MainWindow.setTabOrder(self.lineEdit_rub, self.lineEdit_usd)
        MainWindow.setTabOrder(self.lineEdit_usd, self.lineEdit_rates_rub)
        MainWindow.setTabOrder(self.lineEdit_rates_rub, self.lineEdit_rates_usd)
        MainWindow.setTabOrder(self.lineEdit_rates_usd, self.lineEdit_rates_evr)
        MainWindow.setTabOrder(self.lineEdit_rates_evr, self.lineEdit_byn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_rates_title_name.setText(_translate("MainWindow", "Валюта"))
        self.label_rates_title_rate.setText(_translate("MainWindow", "Курс"))
        self.label_rates_title_date.setText(_translate("MainWindow", "Дата"))
        self.label_rates_evr.setText(_translate("MainWindow", "Евро"))
        self.lineEdit_rates_evr.setText(_translate("MainWindow", "2.2"))
        self.lineEdit_rates_date_evr.setText(_translate("MainWindow", "486"))
        self.label_rates_rub.setText(_translate("MainWindow", "За 100 Российских рублей"))
        self.lineEdit_rates_rub.setText(_translate("MainWindow", "1236"))
        self.lineEdit_rates_date_rub.setText(_translate("MainWindow", "456"))
        self.label_rates_usd.setText(_translate("MainWindow", "Доллар США"))
        self.lineEdit_rates_usd.setText(_translate("MainWindow", "456"))
        self.lineEdit_rates_date_usd.setText(_translate("MainWindow", "456"))
        self.lineEdit_usd.setText(_translate("MainWindow", "200"))
        self.lineEdit_rub.setText(_translate("MainWindow", "8400", "1"))
        self.lineEdit_byn.setText(_translate("MainWindow", "4500"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bill), _translate("MainWindow", "Счёт"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_history), _translate("MainWindow", "История"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_planning), _translate("MainWindow", "Планирование"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_write), _translate("MainWindow", "Запись"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionIncome.setText(_translate("MainWindow", "Поступление"))
        self.actionIncome.setIconText(_translate("MainWindow", "Поступление"))
        self.actionIncome.setToolTip(_translate("MainWindow", "Поступдение средств"))
        self.actionOutcome.setText(_translate("MainWindow", "Расход"))
        self.actionOutcome.setToolTip(_translate("MainWindow", "Расход"))
        self.actionNewCategory.setText(_translate("MainWindow", "Добавить категорию"))
        self.actionNewCategory.setToolTip(_translate("MainWindow", "Добавить категорию"))
        self.actionEditCategory.setText(_translate("MainWindow", "Редактировать категорию"))
        self.actionEditCategory.setToolTip(_translate("MainWindow", "Редактировать категорию"))
from Design import resources_rc
